### ISSUE TITLE
[Feature Request] Create a sensor with light data

### ISSUE THREAD

**Issue by ahmadtawakol** [haberda/update_lights#2]
Instead of the app controlling the lights directly, can it create a sensor with all the light data so we can use it in our automations?

**Comment by haberda** [comment]
This is possible. It would take some effort to get it to work. Currently there are checks whether or not any lights are defined, all of that code would have to be altered. For now, if you create a dummy light with MQTT or something you can define a sensor that reports the dim percentage (see readme). So you could take that, invert the sensor and use it elsewhere.
