### ISSUE TITLE
Problem installing?

### ISSUE THREAD

**Issue by dennisbrouwer91** [haberda/update_lights#3]
Hi,

I installed this module with HACS and then followed your readme, created an apps.yaml, set config and did an include in my main configuration and then Home-Asssistant says : Component error: apps - Integration 'apps' not found..

What can i do to fix this?

**Comment by haberda** [comment]
This is an AppDaemon app, not a custom component. It sounds like you are not currently running AppDaemon. If you are running HassIO then installation of AppDaemon is fairly easy, just install the addon and follow the configuration instructions:

https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html

apps.yaml is used by AppDaemon to setup the apps you want to run.
