### ISSUE TITLE
I don't understand how to achieve a pattern that follows the sun's

### ISSUE THREAD

**Issue by coaxial** [haberda/update_lights#8]
I have a hard time understanding if this is what I need and how to achieve it.

I'd like to have the lights temperature and brightness roughly follow the sun's: bright and cooler in the morning gradually moving towards warm and low brightness as the sun sets, warmest and lowest brightness overnight, gradually increasing back close to sunrise.

Is that what this code achieves? I can't figure out how to set `start_time` and `end_time` to achieve this effect. And do I need `start_index` and `end_index` at all in that scenario?

**Comment by haberda** [comment]
This is exactly what this app achieves. The _index variables are for fine tuning and I wound not use those variables at first. I will post an in-depth explanation on the ReadMe in a couple of days. For now, if you are interested you can read [this](https://github.com/haberda/update_lights/issues/4). 

In any case, the simplest case is to simply follow the sunrise, sunset which is what the end_time and start_time default to respectively. If you find the lights are too bright at a given time you can adjust the start or end times accordingly. The indexes come into play when you are unsatisfied with both ends (both too bright, both too dim).

Keep in mind, the point at which the lights are most dim is the middle between the start and end times. So if you set the start time earlier the lights will be dimmer earlier. The opposite is true for the end time.

The start and end times can be any time string not just sunrise and sunset.

I am working on a new release in the next few days with an improved algorithm, but I have been using this version for months at home and it works well (IMHO).

Also, if you want something dead simple I made a [blueprint](https://community.home-assistant.io/t/periodic-light-blueprint-automatically-adjust-your-lights-with-the-power-of-trigonometry/259767) that works very similar to this.
